import {
  NextRequest,
  NextResponse,
} from "next/server";

import {
  cookies,
} from "next/headers";


export const dynamic =
  "force-dynamic";


const BACKEND_URL =
  process.env.BACKEND_API_URL ??
  "http://127.0.0.1:8000";


const AUTH_COOKIE_NAME =
  process.env.AUTH_COOKIE_NAME ??
  "rippleproof_access_token";


function getBackendUrl(
  request: NextRequest,
  path: string[]
): string {
  const cleanBase =
    BACKEND_URL.replace(
      /\/+$/,
      ""
    );


  const cleanPath =
    path
      .map(
        (part) =>
          encodeURIComponent(
            decodeURIComponent(
              part
            )
          )
      )
      .join("/");


  const search =
    request.nextUrl.search;


  return (
    `${cleanBase}/${cleanPath}${search}`
  );
}


async function getAccessToken():
Promise<string | null> {
  const cookieStore =
    await cookies();


  /*
   * Main production cookie.
   */
  const configured =
    cookieStore.get(
      AUTH_COOKIE_NAME
    )?.value;


  if (configured) {
    return configured;
  }


  /*
   * Compatibility fallbacks.
   * Helpful if older auth step used
   * one of these cookie names.
   */
  return (
    cookieStore.get(
      "rippleproof_access_token"
    )?.value ??
    cookieStore.get(
      "access_token"
    )?.value ??
    cookieStore.get(
      "rippleproof_token"
    )?.value ??
    null
  );
}


function createForwardHeaders(
  request: NextRequest
): Headers {
  const headers =
    new Headers();


  const contentType =
    request.headers.get(
      "content-type"
    );


  const accept =
    request.headers.get(
      "accept"
    );


  const requestId =
    request.headers.get(
      "x-request-id"
    );


  const teamId =
    request.headers.get(
      "x-team-id"
    );


  if (contentType) {
    headers.set(
      "Content-Type",
      contentType
    );
  }


  if (accept) {
    headers.set(
      "Accept",
      accept
    );
  } else {
    headers.set(
      "Accept",
      "application/json"
    );
  }


  if (requestId) {
    headers.set(
      "X-Request-ID",
      requestId
    );
  }


  if (teamId) {
    headers.set(
      "X-Team-ID",
      teamId
    );
  }


  return headers;
}


async function proxyRequest(
  request: NextRequest,
  context: {
    params:
      Promise<{
        path: string[];
      }>;
  }
) {
  try {
    const {
      path,
    } =
      await context.params;


    const targetUrl =
      getBackendUrl(
        request,
        path
      );


    const headers =
      createForwardHeaders(
        request
      );


    const token =
      await getAccessToken();


    if (token) {
      headers.set(
        "Authorization",
        `Bearer ${token}`
      );
    }


    const method =
      request.method.toUpperCase();


    let body:
      ArrayBuffer |
      undefined;


    if (
      method !== "GET" &&
      method !== "HEAD"
    ) {
      body =
        await request.arrayBuffer();
    }


    const backendResponse =
      await fetch(
        targetUrl,
        {
          method,

          headers,

          body:
            body &&
            body.byteLength > 0
              ? body
              : undefined,

          cache:
            "no-store",

          redirect:
            "manual",
        }
      );


    const responseBody =
      await backendResponse.arrayBuffer();


    const responseHeaders =
      new Headers();


    backendResponse.headers.forEach(
      (
        value,
        key
      ) => {
        const lower =
          key.toLowerCase();


        /*
         * Do not forward transport-level
         * headers generated by backend.
         */
        if (
          lower ===
            "content-length" ||
          lower ===
            "content-encoding" ||
          lower ===
            "transfer-encoding" ||
          lower ===
            "connection"
        ) {
          return;
        }


        responseHeaders.set(
          key,
          value
        );
      }
    );


    return new NextResponse(
      responseBody,
      {
        status:
          backendResponse.status,

        statusText:
          backendResponse.statusText,

        headers:
          responseHeaders,
      }
    );

  } catch (error) {
    console.error(
      "RippleProof backend proxy error:",
      error
    );


    return NextResponse.json(
      {
        error: {
          code:
            "BACKEND_UNAVAILABLE",

          message:
            "RippleProof backend is currently unavailable. Please try again.",
        },
      },
      {
        status: 503,
      }
    );
  }
}


export async function GET(
  request: NextRequest,
  context: {
    params:
      Promise<{
        path: string[];
      }>;
  }
) {
  return proxyRequest(
    request,
    context
  );
}


export async function POST(
  request: NextRequest,
  context: {
    params:
      Promise<{
        path: string[];
      }>;
  }
) {
  return proxyRequest(
    request,
    context
  );
}


export async function PUT(
  request: NextRequest,
  context: {
    params:
      Promise<{
        path: string[];
      }>;
  }
) {
  return proxyRequest(
    request,
    context
  );
}


export async function PATCH(
  request: NextRequest,
  context: {
    params:
      Promise<{
        path: string[];
      }>;
  }
) {
  return proxyRequest(
    request,
    context
  );
}


export async function DELETE(
  request: NextRequest,
  context: {
    params:
      Promise<{
        path: string[];
      }>;
  }
) {
  return proxyRequest(
    request,
    context
  );
}


export async function OPTIONS(
  request: NextRequest,
  context: {
    params:
      Promise<{
        path: string[];
      }>;
  }
) {
  return proxyRequest(
    request,
    context
  );
}